input.onPinPressed(TouchPin.P0, function () {
    music.playMelody("B C G A C5 C5 B B ", 1550)
    music.playMelody("D D E E C C E E ", 1550)
    music.playMelody("E C G C E C G C ", 3100)
    music.playMelody("A A A A G G G G ", 3100)
    music.playMelody("E C G C E C G C ", 3100)
    music.playMelody("A A A A G G G G ", 3100)
    music.playMelody("E E C C E E E E ", 775)
    music.playMelody("E G B E G B C5 B ", 775)
})
input.onButtonPressed(Button.A, function () {
    music.playMelody("E G B A E G B A ", 390)
    music.playMelody("C C D D E E G G ", 390)
    music.playMelody("F G A B F G C5 A ", 390)
    music.playMelody("A G A G C5 B C5 B ", 1460)
    music.playMelody("A G A G C5 B C5 B ", 1460)
    music.playMelody("A G A G C5 B C5 B ", 1460)
    music.playMelody("A G A G C5 B C5 B ", 1460)
    music.playMelody("E - - - - - - - ", 195)
})
input.onPinPressed(TouchPin.P2, function () {
    music.playMelody("E C E G C5 C5 B A ", 310)
    music.playMelody("G E G A G E G A ", 620)
    music.playMelody("D D E D C C C C ", 620)
})
input.onButtonPressed(Button.B, function () {
    music.playMelody("B E G B E G C5 B ", 235)
    music.playMelody("E C G C B A G F ", 470)
    music.playMelody("E E D D C C C C ", 470)
})
input.onPinPressed(TouchPin.P1, function () {
    music.playMelody("B G D B G D A B ", 450)
    music.playMelody("C5 B G D C5 B G D ", 900)
    music.playMelody("D C G D D C G D ", 900)
    music.playMelody("D D G G D D G G ", 450)
    music.playMelody("A C5 D G C5 A G D ", 450)
})
hummingbird.startHummingbird()
music.playMelody("B G A G E E G G ", 270)
music.playMelody("C C D D E E G G ", 270)
music.playMelody("A G B G C5 G D G ", 540)
music.playMelody("G E C E G G A A ", 540)
music.playMelody("B B D E D D G G ", 270)
basic.forever(function () {
    basic.showString("Pick a song to play")
})
